<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UsernamePassword did not match</name>
   <tag></tag>
   <elementGuidId>db82432f-ccf2-4e80-b7a6-6b2ff0dd2559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='reason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e48b1246-0fc4-47a0-a83c-13a1cd16687c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>d15b19f1-2f1f-4df5-9bea-c7644b6772f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username/Password did not match</value>
      <webElementGuid>16dec5a4-137d-42e9-bf9d-28f43200e820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reason&quot;)</value>
      <webElementGuid>61d77ac3-36e3-49f1-a4a8-e27f67be4073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='reason']</value>
      <webElementGuid>c10b42b5-d587-4ce6-a86e-1527e0e04520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-alert']/span</value>
      <webElementGuid>5e27c5ff-97a8-4537-bdac-3d5d474b93e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation Failed'])[1]/following::span[1]</value>
      <webElementGuid>f84fa3af-4f1e-4edb-9ddd-70faa0bd4f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::span[1]</value>
      <webElementGuid>4b36ffd5-05b3-4637-9cfb-1ff646fdf1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::span[1]</value>
      <webElementGuid>71ec3209-6b0f-4cf6-9b45-59660782b010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username/Password did not match']/parent::*</value>
      <webElementGuid>a090e5c8-626c-4beb-bf34-c527f881855c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>cbba3671-fe79-455d-8ba7-7abb02745c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'reason' and (text() = 'Username/Password did not match' or . = 'Username/Password did not match')]</value>
      <webElementGuid>6f6a8053-d8a7-45de-b99f-d71c2e0545ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
